### ISSUE TITLE
[Question] Issue with starting app

### ISSUE THREAD

**Issue by OpenSource03** [QIN2DIM/hcaptcha-challenger#107]
Hello there!

I'm having an issue starting the app. Here is the log:

```
(venv) dejanzegarac@Dejans-Mac-Studio src % python main.py test
[WDM] - Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.28M/7.28M [00:00<00:00, 14.3MB/s]
2022-07-30 22:23:27 | DEBUG - 🎮 Activate challenger context
2022-07-30 22:23:29 | ERROR - An error has been caught in function 'test', process 'MainProcess' (87916), thread 'MainThread' (9141240512):
Traceback (most recent call last):
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/src/services/utils/toolbox/toolbox.py", line 105, in get_challenge_ctx
    return uc.Chrome(
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/venv/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/venv/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/venv/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/venv/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /Users/dejanzegarac/.wdm/drivers/chromedriver/mac64_m1/103.0.5060/chromedriver unexpectedly exited. Status code was: -9


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/venv/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/venv/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/venv/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/src/services/scaffold.py", line 29, in test
    challenge.test()
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/src/apis/scaffold/challenge.py", line 91, in test
    ctx = get_challenge_ctx(silence=True)
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/src/services/utils/toolbox/toolbox.py", line 109, in get_challenge_ctx
    return uc.Chrome(
  File "/Users/dejanzegarac/PycharmProjects/hcaptcha-challenger/venv/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 244, in __init__
    raise RuntimeError("you cannot reuse the ChromeOptions object")
RuntimeError: you cannot reuse the ChromeOptions object
```

Any suggestions?

**Comment by QIN2DIM** [comment]
kill all chromedriver process

**Comment by QIN2DIM** [comment]
`undetected-chromedriver` does not allow different processes to reuse the same chromedriver.

**Comment by whhsw** [comment]
遇到了同样的问题，所有的chrome process都已经关掉了。 初步怀疑是因为 chromedriver 在/usr/local/bin 中也有配置（其他项目在使用）。不知道代码中是否有什么地方call了 chromedriver关键词，才导致driver会被启动两次？

**Comment by QIN2DIM** [comment]
>  初步怀疑是因为 chromedriver 在/usr/local/bin 中也有配置（其他项目在使用）

是这样的，所以我一直很想加个 catch 绕过这个 exception，我个人觉得是不影响的。或者在检测到驱动重用后拷贝一个文件，不知道这样能不能行得通，我还没试过。
