### ISSUE TITLE
[Question] Warning None

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#296]
022-10-23 23:13:54 | DEBUG - Downloading objects.yaml from https://raw.githubusercontent.com/QIN2DIM/hcaptcha-challenger/main/src/objects.yaml
2022-10-23 23:14:02 | WARNING - None
2022-10-23 23:14:06 | WARNING - None
2022-10-23 23:14:10 | WARNING - None
2022-10-23 23:14:14 | WARNING - None
2022-10-23 23:14:17 | WARNING - None
2022-10-23 23:14:21 | WARNING - None
2022-10-23 23:14:25 | WARNING - None
2022-10-23 23:14:29 | WARNING - None

this issue persist

The object in this case is cup of coffee, it takes screenshot, then take again and so on

**Comment by M-Zubair10** [comment]
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\Selenium-master\CaptchaSolutions\captchasolver.py", line 639, in solve
    self._response = self.hcaptcha()
  File "C:\Users\HP\PycharmProjects\Selenium-master\CaptchaSolutions\captchasolver.py", line 429, in hcaptcha
    hit_challenge(ctx=self.driver, challenger=challenger)
  File "C:\Users\HP\PycharmProjects\Selenium-master\CaptchaSolutions\captchasolver.py", line 419, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\HP\PycharmProjects\Selenium-master\venv\lib\site-packages\hcaptcha_challenger\core.py", line 671, in anti_hcaptcha
    if drop := self.get_label(ctx) in [self.CHALLENGE_BACKCALL]:
  File "C:\Users\HP\PycharmProjects\Selenium-master\venv\lib\site-packages\hcaptcha_challenger\core.py", line 339, in get_label
    label_obj = WebDriverWait(
  File "C:\Users\HP\PycharmProjects\Selenium-master\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 81, in until
    value = method(self._driver)
  File "C:\Users\HP\PycharmProjects\Selenium-master\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 64, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\HP\PycharmProjects\Selenium-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\HP\PycharmProjects\Selenium-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\HP\PycharmProjects\Selenium-master\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=106.0.5249.103)
Stacktrace:
Backtrace:
	Ordinal0 [0x00BB1ED3+2236115]
	Ordinal0 [0x00B492F1+1807089]
	Ordinal0 [0x00A566FD+812797]
	Ordinal0 [0x00A3DFFA+712698]
	Ordinal0 [0x00AA506B+1134699]
	Ordinal0 [0x00AB514A+1200458]
	Ordinal0 [0x00AA18A6+1120422]
	Ordinal0 [0x00A7A73D+960317]
	Ordinal0 [0x00A7B71F+964383]
	GetHandleVerifier [0x00E5E7E2+2743074]
	GetHandleVerifier [0x00E508D4+2685972]
	GetHandleVerifier [0x00C42BAA+532202]
	GetHandleVerifier [0x00C41990+527568]
	Ordinal0 [0x00B5080C+1837068]
	Ordinal0 [0x00B54CD8+1854680]
	Ordinal0 [0x00B54DC5+1854917]
	Ordinal0 [0x00B5ED64+1895780]
	BaseThreadInitThunk [0x74E7FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76F47B5E+286]
	RtlGetAppContainerNamedObjectPath [0x76F47B2E+238]

Note, i quit window as this error happens 6 times in row

**Comment by QIN2DIM** [comment]
That's another project.

**Comment by M-Zubair10** [comment]
2022-10-23 23:14:02.868 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:14:06.693 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:14:10.731 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:14:14.459 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:14:17.980 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:14:21.545 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:14:25.971 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:14:29.805 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:19:41.142 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:19:45.387 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:19:48.895 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:19:52.758 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:20:14.669 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:20:18.311 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:20:26.771 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:20:30.972 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:20:34.755 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None
2022-10-23 23:20:38.706 | WARNING  | hcaptcha_challenger.core:tactical_retreat:389 - None

**Comment by M-Zubair10** [comment]
what do you mean, i am using hcaptchachallenger pypi version

**Comment by QIN2DIM** [comment]
This is the invalid log.  But maybe it's a bug

**Comment by M-Zubair10** [comment]
Please check now.
I tried it many times but still it stuck in there

**Comment by QIN2DIM** [comment]
What I mean is that the program kept the challenge screenshot at the same time when this line of the log appeared(` hcaptcha_challenger.core:tactical_retreat:xxx`).

You have to learn to ask questions, otherwise these are invalid information and do not help you solve the problem.

**Comment by M-Zubair10** [comment]
Thank you!
What are guidelines to ask a question

Do you need a screenshot, where does it saved?
Tempcache?

**Comment by M-Zubair10** [comment]
Here's the screenshot
![1666548846 cup of coffee](https://user-images.githubusercontent.com/47709300/197413950-619f3765-055f-4434-aabc-3d44ffacd3e5.png)
![1666548853 cup of coffee](https://user-images.githubusercontent.com/47709300/197414005-ff490cc5-e9cf-42f3-904c-7414817a1699.png)


See both are same images, it took screenshot print warning message and retry and this happens continuously

**Comment by QIN2DIM** [comment]
what's your pkg-version of the hcaptcha-challegner

**Comment by QIN2DIM** [comment]
maybe new badcode ?

**Comment by M-Zubair10** [comment]
Its 0.4.2.17

**Comment by M-Zubair10** [comment]
Please in new pypi version, update this

#258

**Comment by QIN2DIM** [comment]
I'm considering replacing Selenium with Playwright, or adding another interface model

Selenium is too slow to run in this scenario

**Comment by M-Zubair10** [comment]
As you wish, but please make pypi version accept ctx as it before, since
all my work is done in selenium

**Comment by QIN2DIM** [comment]
shit

![image](https://user-images.githubusercontent.com/62018067/197415264-dbc84946-4af9-410a-a8b1-e40fb7e20e5b.png)

**Comment by QIN2DIM** [comment]
well done  - -

**Comment by QIN2DIM** [comment]
https://github.com/QIN2DIM/hcaptcha-challenger/commit/32aff479825c6db7996ac8afe27b968b4ec5561d

**Comment by QIN2DIM** [comment]
you can also type `pip install -U hcaptcha-challenge` to check it.

**Comment by M-Zubair10** [comment]
Thanks, will it update automatically objects.yaml
