### ISSUE TITLE
[Question] Cannot pass 'python3 main.py test'

### ISSUE THREAD

**Issue by Jonathan0827** [QIN2DIM/hcaptcha-challenger#392]
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>

**Comment by QIN2DIM** [comment]
Did you open a system proxy?

**Comment by Jonathan0827** [comment]
No

**Comment by QIN2DIM** [comment]
Provide more information, otherwise this issue will be complicated.

**Comment by Jonathan0827** [comment]
like what?

**Comment by QIN2DIM** [comment]
emmm... full log？

**Comment by QIN2DIM** [comment]
I guess you may have a problem in the automatic download chromedriver stage

**Comment by Jonathan0827** [comment]
2023-01-15 14:06:30 | DEBUG - 🎮 Activate challenger context
2023-01-15 14:06:31 | ERROR - An error has been caught in function 'demo', process 'MainProcess' (20136), thread 'MainThread' (4305716608):
Traceback (most recent call last):
  File "/Users/jonathanlim/hcaptcha-challenger/hcaptcha_challenger/_scaffold/__init__.py", line 163, in get_challenge_ctx
    return uc.Chrome(
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/undetected_chromedriver/__init__.py", line 431, in __init__
    super(Chrome, self).__init__(
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/common/service.py", line 106, in start
    self.assert_process_still_running()
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/common/service.py", line 119, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /Users/jonathanlim/.wdm/drivers/chromedriver/mac_arm64/109.0.5414/chromedriver unexpectedly exited. Status code was: -9


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1345, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jonathanlim/hcaptcha-challenger/main.py", line 117, in <module>
    Fire(Scaffold)
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/Users/jonathanlim/hcaptcha-challenger/main.py", line 86, in demo
    demo_challenge.run(
  File "/Users/jonathanlim/hcaptcha-challenger/examples/demo_challenge.py", line 58, in run
    ctx = solver.get_challenge_ctx(silence=silence, lang=lang)
  File "/Users/jonathanlim/hcaptcha-challenger/hcaptcha_challenger/_scaffold/__init__.py", line 170, in get_challenge_ctx
    return uc.Chrome(
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/undetected_chromedriver/__init__.py", line 246, in __init__
    patcher.auto()
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/undetected_chromedriver/patcher.py", line 130, in auto
    release = self.fetch_release_number()
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/undetected_chromedriver/patcher.py", line 151, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 213, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 516, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 533, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 493, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1388, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1348, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>

**Comment by Jonathan0827** [comment]
M1 MacBook Air with macOS 12.6.1

**Comment by QIN2DIM** [comment]
```python
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/undetected_chromedriver/patcher.py", line 151, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())

```

**Comment by QIN2DIM** [comment]
`pip install urllib3==1.25.11`

**Comment by Jonathan0827** [comment]
Hmm, I think this doesn't work
