### ISSUE TITLE
[Question] RuntimeError: you cannot reuse the ChromeOptions object

### ISSUE THREAD

**Issue by Jonathan0827** [QIN2DIM/hcaptcha-challenger#393]
```
python3 main.py test
```
```
2023-01-15 15:53:26 | DEBUG - 🎮 Activate challenger context
2023-01-15 15:53:27 | ERROR - An error has been caught in function 'demo', process 'MainProcess' (26244), thread 'MainThread' (4373284224):
Traceback (most recent call last):
  File "/Users/jonathanlim/hcaptcha-challenger-v1/hcaptcha_challenger/_scaffold/__init__.py", line 163, in get_challenge_ctx
    return uc.Chrome(
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/undetected_chromedriver/__init__.py", line 431, in __init__
    super(Chrome, self).__init__(
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/common/service.py", line 106, in start
    self.assert_process_still_running()
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/common/service.py", line 119, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /Users/jonathanlim/.wdm/drivers/chromedriver/mac_arm64/109.0.5414/chromedriver unexpectedly exited. Status code was: -9


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jonathanlim/hcaptcha-challenger-v1/main.py", line 120, in <module>
    Fire(Scaffold)
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/Users/jonathanlim/hcaptcha-challenger-v1/main.py", line 89, in demo
    demo_challenge.run(
  File "/Users/jonathanlim/hcaptcha-challenger-v1/examples/demo_challenge.py", line 58, in run
    ctx = solver.get_challenge_ctx(silence=silence, lang=lang)
  File "/Users/jonathanlim/hcaptcha-challenger-v1/hcaptcha_challenger/_scaffold/__init__.py", line 170, in get_challenge_ctx
    return uc.Chrome(
  File "/Users/jonathanlim/Library/Python/3.9/lib/python/site-packages/undetected_chromedriver/__init__.py", line 256, in __init__
    raise RuntimeError("you cannot reuse the ChromeOptions object")
RuntimeError: you cannot reuse the ChromeOptions object
```

**Comment by QIN2DIM** [comment]
I guess https://github.com/QIN2DIM/hcaptcha-challenger/issues/233
