### ISSUE TITLE
[Question] Aiohttp ConnectionResetError

### ISSUE THREAD

**Issue by reactiver001** [QIN2DIM/hcaptcha-challenger#41]
But i have this error all time 
Thanks for all

I try use this command : 

```markdown

>python main.py demo --lang=en


2022-05-02 13:17:54 | INFO - Starting demo project...
2022-05-02 13:17:54 | DEBUG - 🎮 Activate challenger context
2022-05-02 13:17:57 | DEBUG - >> Challenge [ArmorCaptcha] Handle hCaptcha checkbox
2022-05-02 13:17:58 | DEBUG - >> Challenge [ArmorCaptcha] Get label - label=「airplane」
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<AshFramework.launcher() done, defined at C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\utils\accelerator\core.py:49> exception=ClientConnectorError(ConnectionKey(host='imgs.hcaptcha.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1120, in _create_connection_transport
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\selector_events.py", line 853, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\utils\accelerator\core.py", line 53, in launcher
    await self.control_driver(context, session=session)
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\hcaptcha_challenger\core.py", line 272, in control_driver
    async with session.get(url) as response:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host imgs.hcaptcha.com:443 ssl:default [An existing connection was forcibly closed by the remote host]
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<AshFramework.launcher() done, defined at C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\utils\accelerator\core.py:49> exception=ClientConnectorError(ConnectionKey(host='imgs.hcaptcha.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1120, in _create_connection_transport
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\selector_events.py", line 853, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\utils\accelerator\core.py", line 53, in launcher
    await self.control_driver(context, session=session)
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\hcaptcha_challenger\core.py", line 272, in control_driver
    async with session.get(url) as response:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host imgs.hcaptcha.com:443 ssl:default [An existing connection was forcibly closed by the remote host]
2022-05-02 13:17:59 | DEBUG - >> Challenge [ArmorCaptcha] Download the challenge image
[EXIT] Press any key to exit...
2022-05-02 13:18:00 | ERROR - An error has been caught in function 'demo', process 'MainProcess' (1384), thread 'MainThread' (8236):
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\main.py", line 11, in <module>
    Fire(Scaffold)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\scaffold.py", line 54, in demo
    challenge.runner(
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\apis\scaffold\challenge.py", line 50, in runner
    resp = challenger.anti_hcaptcha(ctx, dir_model=DIR_MODEL, onnx_prefix=onnx_prefix)
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\hcaptcha_challenger\core.py", line 503, in anti_hcaptcha
    self.challenge(ctx, model=model)
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\hcaptcha_challenger\core.py", line 320, in challenge
    with open(img_filepath, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\hcaptcha2\\hcaptcha-challenger\\src\\database\\temp_cache\\_challenge\\1651493879_aeroplane\\Challenge Image 2.png'
```

**Comment by QIN2DIM** [comment]
……

**Comment by QIN2DIM** [comment]
Are you using a proxy?

**Comment by reactiver001** [comment]
Dont use proxy , i try in my computer and server and have the same problem .

**Comment by QIN2DIM** [comment]
Maybe you should provide more information - like chrome version or something otherwise I would never have guessed the problem.

**Comment by reactiver001** [comment]
My version chrome is : 101.0.4951.54
I did git clone , went to the directory installed everything and then tried to run the script and had this problem above

**Comment by QIN2DIM** [comment]
I suddenly realized that this was an interesting question.

**Comment by reactiver001** [comment]
Hello ,, update version for python 3,10 and now work better , but sometimes have this, I think it's the Challenge that has changed
Note : Run in my server without proxy

C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src>py -3.10 main.py demo --lang=en
2022-05-06 17:59:26 | INFO - Starting demo project...
2022-05-06 17:59:28 | DEBUG - 🎮 Activate challenger context
2022-05-06 17:59:31 | DEBUG - >> Challenge [ArmorCaptcha] Handle hCaptcha checkbox
2022-05-06 17:59:32 | DEBUG - >> Challenge [ArmorCaptcha] Get label - label=「motorbus」
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<AshFramework.launcher() done, defined at C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\utils\accelerator\core.py:49> exception=ClientConnectorError(ConnectionKey(host='imgs.hcaptcha.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 853, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\utils\accelerator\core.py", line 53, in launcher
    await self.control_driver(context, session=session)
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\hcaptcha_challenger\core.py", line 272, in control_driver
    async with session.get(url) as response:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host imgs.hcaptcha.com:443 ssl:default [An existing connection was forcibly closed by the remote host]
2022-05-06 17:59:33 | DEBUG - >> Challenge [ArmorCaptcha] Download the challenge image
[EXIT] Press any key to exit...
2022-05-06 17:59:34 | ERROR - An error has been caught in function 'demo', process 'MainProcess' (10176), thread 'MainThread' (6308):
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\main.py", line 11, in <module>
    Fire(Scaffold)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\scaffold.py", line 54, in demo
    challenge.runner(
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\apis\scaffold\challenge.py", line 50, in runner
    resp = challenger.anti_hcaptcha(ctx, dir_model=DIR_MODEL, onnx_prefix=onnx_prefix)
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\hcaptcha_challenger\core.py", line 503, in anti_hcaptcha
    self.challenge(ctx, model=model)
  File "C:\Users\Administrator\Desktop\hcaptcha2\hcaptcha-challenger\src\services\hcaptcha_challenger\core.py", line 320, in challenge
    with open(img_filepath, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\hcaptcha2\\hcaptcha-challenger\\src\\database\\temp_cache\\_challenge\\1651856373_bus\\Challenge Image 2.png'

**Comment by QIN2DIM** [comment]
我确信是你的网络有问题，但这通常是偶发的异常，也许你的网络配置比较特殊。

**Comment by QIN2DIM** [comment]
你用的是最新的代码吗？还是过期的。
