### ISSUE TITLE
[Question] AttributeError: has no attribute 'YOLOAirplane'

### ISSUE THREAD

**Issue by SoloQTKiller** [QIN2DIM/hcaptcha-challenger#51]
When running the project today I come across the following error in the logs. Previously it was solving all captchas correctly but now all it does is return the following error and it doesn't solve anything

```markdown
2022-06-05 13:47:10.452 | DEBUG    | services.utils.toolbox.toolbox:get_challenge_ctx:93 - 🎮 Activate challenger context
2022-06-05 13:47:15.540 | DEBUG    | services.hcaptcha_challenger.core:log:143 - >> Challenge [ArmorCaptcha] Handle hCaptcha checkbox
2022-06-05 13:47:18.788 | DEBUG    | services.hcaptcha_challenger.core:log:143 - >> Challenge [ArmorCaptcha] Get label - label=「飞机」
2022-06-05 13:47:22.069 | DEBUG    | services.hcaptcha_challenger.core:log:143 - >> Challenge [ArmorCaptcha] Download the challenge image
2022-06-05 13:47:25.670 | ERROR    | services.scaffold:demo:54 - An error has been caught in function 'demo', process 'MainProcess' (25436), thread 'MainThread' (8040):
Traceback (most recent call last):
  File "C:\Users\felip\Desktop\Account Creator v3\src\main.py", line 24, in <module>
    Scaffold.demo()
> File "C:\Users\felip\Desktop\Account Creator v3\src\services\scaffold.py", line 54, in demo
    challenge.runner(
  File "C:\Users\felip\Desktop\Account Creator v3\src\apis\scaffold\challenge.py", line 77, in runner
    resp = challenger.anti_hcaptcha(ctx, dir_model=DIR_MODEL, onnx_prefix=onnx_prefix)
  File "C:\Users\felip\Desktop\Account Creator v3\src\services\hcaptcha_challenger\core.py", line 502, in anti_hcaptcha
    model = self.switch_solution(dir_model, onnx_prefix)
  File "C:\Users\felip\Desktop\Account Creator v3\src\services\hcaptcha_challenger\core.py", line 206, in switch_solution
    return yolo.YOLOAirplane(dir_model, onnx_prefix, path_rainbow=PATH_RAINBOW)
AttributeError: module 'services.hcaptcha_challenger.solutions.yolo' has no attribute 'YOLOAirplane'
2022-06-05 13:47:27.085 | DEBUG    | services.utils.toolbox.toolbox:get_challenge_ctx:93 - 🎮 Activate challenger context
```

**Comment by QIN2DIM** [comment]
If you can't provide more details, this looks like just a basic syntax issue.

**Comment by QIN2DIM** [comment]
re-clone your code
