### ISSUE TITLE
[Question] please i wanna know how can i use this with my typescript playwright script 

### ISSUE THREAD

**Issue by UnixCr3wR0x** [QIN2DIM/hcaptcha-challenger#523]
## Brief description

i just wanna know how can i integrate my playwright bot to use this library i believe there is a way i wanna know if some1 made it b4 or what

**Comment by yurhett** [comment]
I think you should separate hcaptcha-challenger as a python api, then call the api in your typescipt.

**Comment by UnixCr3wR0x** [comment]
thanks a lot for responding to this but the problem is how can i use it in the first place?
its kinda stupid question i know sorry for that i have never developed things on python

**Comment by UnixCr3wR0x** [comment]
does it work with url and site key only ?

**Comment by yurhett** [comment]
Unfortunately not. This isnot a web service, you should deploy yourself. Try to understand Python flask and then try this one https://github.com/M-Zubair10/CaptchaXpert

**Comment by UnixCr3wR0x** [comment]
wow thanks a lot for ur help i will try it and i will get back to u but again thanks a lot <3

**Comment by UnixCr3wR0x** [comment]
unfortunately i cant make it work i got this errors 

when trying to run the captchaxpert captchasolver test module 
`2023-04-25 01:30:56,232 - __main__ - INFO - ====== Results ======
Responses: [(True, 7.799), (True, 4.991)]
Counter: Counter({True: 2})
Time: 12.79
Traceback (most recent call last):
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000028D0B5E0D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /resolve (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028D0B5E0D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\code-base\my tools\CaptchaXpert\api\testcase.py", line 138, in <module>
    run_recaptcha_v2_test()
  File "E:\code-base\my tools\CaptchaXpert\api\testcase.py", line 56, in wrapper
    return n_tests(func, *args, **kwargs)
  File "E:\code-base\my tools\CaptchaXpert\api\testcase.py", line 71, in n_tests
    result = func(*args, **kwargs)
  File "E:\code-base\my tools\CaptchaXpert\api\testcase.py", line 83, in run_recaptcha_v2_test
    return solver.solve()
  File "E:\code-base\my tools\CaptchaXpert\api\__init__.py", line 29, in wrapper
    raise e
  File "E:\code-base\my tools\CaptchaXpert\api\__init__.py", line 25, in wrapper
    return func(self, *args, **kwargs)
  File "E:\code-base\my tools\CaptchaXpert\api\__init__.py", line 231, in solve
    self.RESPONSE = self.recaptcha_v2.RecaptchaV2(self.HOST, self.driver, self.wait, self.timeout,
  File "E:\code-base\my tools\CaptchaXpert\api\solutions\recaptcha\recaptcha_v2.py", line 153, in solve
    response = self._solve()
  File "E:\code-base\my tools\CaptchaXpert\api\solutions\recaptcha\recaptcha_v2.py", line 98, in _solve
    response = requests.post(f"{self.HOST}/resolve", json=data)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Un1xCr3w\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /resolve (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028D0B5E0D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-04-25 01:30:56,617 - undetected_chromedriver.dprocess - DEBUG - cleaning up pid 11776 
2023-04-25 01:31:00,740 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028D0ADA2B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f7575028a56e6a06f65d4239a70a7550
2023-04-25 01:31:04,825 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028D0AC8EC70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f7575028a56e6a06f65d4239a70a7550
2023-04-25 01:31:08,925 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028D0AB2DDC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f7575028a56e6a06f65d4239a70a7550`

**Comment by yurhett** [comment]
That's why I talk about flask. Try to understand Flask. 
You should run web service first. For that project, it is under [CaptchaResolver](https://github.com/M-Zubair10/CaptchaXpert/tree/main/CaptchaResolver) folder. Then the web service will running on the port 5000, according to the manual.

**Comment by UnixCr3wR0x** [comment]
@yurhett yeah i know thats what i have already done but i dont know what is the needed payload to send it
