### ISSUE TITLE
[Question] Error yolov5s6.onnx in function 'cv::dnn::dnn4_v20211220::ONNXImporter::ONNXImporter'

### ISSUE THREAD

**Issue by SoloQTKiller** [QIN2DIM/hcaptcha-challenger#54]
I'm facing the following problem when executing the code on another computer that I have, the error in which it was recorded in the logs is below

```markdown
2022-06-06 22:47:58.433 | ERROR    | services.scaffold:demo:54 - An error has been caught in function 'demo', process 'MainProcess' (6140), thread 'MainThread' (10772):
Traceback (most recent call last):
  File "C:\Users\JUNIOR\Desktop\Divulgação\Nova pasta\Account Creator v3\src\main.py", line 24, in <module>
    Scaffold.demo()
> File "C:\Users\JUNIOR\Desktop\Divulgação\Nova pasta\Account Creator v3\src\services\scaffold.py", line 54, in demo
    challenge.runner(
  File "C:\Users\JUNIOR\Desktop\Divulgação\Nova pasta\Account Creator v3\src\apis\scaffold\challenge.py", line 77, in runner
    resp = challenger.anti_hcaptcha(ctx, dir_model=DIR_MODEL, onnx_prefix=onnx_prefix)
  File "C:\Users\JUNIOR\Desktop\Divulgação\Nova pasta\Account Creator v3\src\services\hcaptcha_challenger\core.py", line 505, in anti_hcaptcha
    self.challenge(ctx, model=model)
  File "C:\Users\JUNIOR\Desktop\Divulgação\Nova pasta\Account Creator v3\src\services\hcaptcha_challenger\core.py", line 327, in challenge
    result = model.solution(img_stream=data, label=self.label_alias[self.label])
  File "C:\Users\JUNIOR\Desktop\Divulgação\Nova pasta\Account Creator v3\src\services\hcaptcha_challenger\solutions\yolo.py", line 179, in solution
    labels = self.detect_common_objects(img_stream, confidence, nms_thresh)
  File "C:\Users\JUNIOR\Desktop\Divulgação\Nova pasta\Account Creator v3\src\services\hcaptcha_challenger\solutions\yolo.py", line 145, in detect_common_objects
    net = cv2.dnn.readNetFromONNX(self.onnx_model["path"])
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:194: error: (-5:Bad argument) Can't read ONNX file: C:\Users\JUNIOR\Desktop\Divulgação\Nova pasta\Account Creator v3\src\model\yolov5s6.onnx in function 'cv::dnn::dnn4_v20211220::ONNXImporter::ONNXImporter'
```

**Comment by QIN2DIM** [comment]
Hey man, why can you encounter so many basic errors, this time there is a problem with the environment dependency.😂

**Comment by SoloQTKiller** [comment]
Could you tell me how to solve this dependency problem? Because I tested it on several computers of other friends and on some they work and on others I didn't want to solve it so they could use it too, and a thousand apologies for asking questions that seem silly but I tried to look for how to solve it and I didn't find anything that worked 😔

**Comment by QIN2DIM** [comment]
Then you should provide all the information, not a few lines of the error log, which doesn't solve any problems.😂

Your model file should be corrupted, download a new one.
