### ISSUE TITLE
[Question] error occured after downloaded the challenge image

### ISSUE THREAD

**Issue by MadLongTom** [QIN2DIM/hcaptcha-challenger#57]
```markdown
Traceback (most recent call last):
  File "C:\Users\GIGABYTE\Desktop\py1\hcaptcha-challenger-main\src\main.py", line 11, in <module>
    Fire(Scaffold)
  File "C:\Users\GIGABYTE\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\GIGABYTE\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\GIGABYTE\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "C:\Users\GIGABYTE\Desktop\py1\hcaptcha-challenger-main\src\services\scaffold.py", line 54, in demo
    challenge.runner(
  File "C:\Users\GIGABYTE\Desktop\py1\hcaptcha-challenger-main\src\apis\scaffold\challenge.py", line 49, in runner
    resp = challenger.anti_hcaptcha(ctx, dir_model=DIR_MODEL, onnx_prefix=onnx_prefix)
  File "C:\Users\GIGABYTE\Desktop\py1\hcaptcha-challenger-main\src\services\hcaptcha_challenger\core.py", line 505, in anti_hcaptcha
    self.challenge(ctx, model=model)
  File "C:\Users\GIGABYTE\Desktop\py1\hcaptcha-challenger-main\src\services\hcaptcha_challenger\core.py", line 327, in challenge
    result = model.solution(img_stream=data, label=self.label_alias[self.label])
  File "C:\Users\GIGABYTE\Desktop\py1\hcaptcha-challenger-main\src\services\hcaptcha_challenger\solutions\yolo.py", line
 190, in solution
    labels = self.detect_common_objects(img, confidence, nms_thresh)
  File "C:\Users\GIGABYTE\Desktop\py1\hcaptcha-challenger-main\src\services\hcaptcha_challenger\solutions\yolo.py", line
 144, in detect_common_objects
    net = cv2.dnn.readNetFromONNX(self.onnx_model["path"])
cv2.error: OpenCV(4.4.0) D:\Build\OpenCV\opencv-4.4.0\modules\dnn\src\onnx\onnx_importer.cpp:1410: error: (-2:Unspecified error) in function 'void __cdecl cv::dnn::dnn4_v20200609::ONNXImporter::populateNet(class cv::dnn::dnn4_v20200609::Net)'
>  (expected: 'shapes.depth() == CV_32S'), where
>     'shapes.depth()' is 5 (CV_32FC1)
> must be equal to
>     'CV_32S' is 4 (CV_32SC1)
```

how to solve it?

**Comment by QIN2DIM** [comment]
Some time has passed, have you solved the problem? I personally think your model file is corrupted, try downloading it again?

**Comment by MadLongTom** [comment]
Solved.I installed the wrong version of opencv-python,any version which higher/lower than required is leading to this error.

**Comment by MadLongTom** [comment]
i tested 4.4.0 and 4.6.0.Both lead to this error.
