### ISSUE TITLE
funcaptcha

### ISSUE THREAD

**Issue by M4Nyak** [QIN2DIM/hcaptcha-challenger#808]
can i train model for funcaptcha with this?

**Comment by QIN2DIM** [comment]
These are two completely different application scenarios

**Comment by M4Nyak** [comment]
2023-10-10 10:20:56 | ERROR - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (6928), thread 'MainThread' (3484):
Traceback (most recent call last):
  File "C:\Users\mrx\Desktop\hcaptcha-model-factory-main\src\main.py", line 6, in <module>
    Fire(Scaffold)
  File "C:\Users\mrx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\mrx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
> File "C:\Users\mrx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\mrx\Desktop\hcaptcha-model-factory-main\src\apis\scaffold.py", line 70, in new
    ClusterLabeler(data_dir=data_dir).run()
  File "C:\Users\mrx\Desktop\hcaptcha-model-factory-main\src\components\auto_label\cluster.py", line 57, in run
    emb = self.img2emb.get_emb(img)
  File "C:\Users\mrx\Desktop\hcaptcha-model-factory-main\src\components\auto_label\img2emb.py", line 98, in get_emb
    image = self.normalize(self.to_tensor(self.scaler(img))).unsqueeze(0).to(self.device)
  File "C:\Users\mrx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mrx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torchvision\transforms\transforms.py", line 277, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "C:\Users\mrx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torchvision\transforms\functional.py", line 363, in normalize
    return F_t.normalize(tensor, mean=mean, std=std, inplace=inplace)
  File "C:\Users\mrx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torchvision\transforms\_functional_tensor.py", line 928, in normalize
    return tensor.sub_(mean).div_(std)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0                                     i took this error

**Comment by M4Nyak** [comment]
i took this error

**Comment by QIN2DIM** [comment]
Can you provide some samples of funcaptcha challenges (binary classification tasks only)

btw, if it's convenient for you, please leave a comment under the `factory` repository.

**Comment by QIN2DIM** [comment]
```python

import shutil
from pathlib import Path

from loguru import logger

from apis.scaffold import Scaffold

# Structure:
#  |- diagnosed_label_name/  # Model alias
#       |- yes/
#           |- *.png         # At least 10 images
#       |- bad/
#           |- *.png         # At least 10 images

# Workflow：
# 1. Copy from: `[PROJECT]/database2309/<diagnosed_label_name>`
# 2. Paste to: `[PROJECT]/data/<diagnosed_label_name>`
# 3. Output to: `[PROJECT]/model/<diagnosed_label_name>/<model_name[version].onnx>`

project_dir = Path(__file__).parent.parent

binary_dir = project_dir.joinpath("database2309")
factory_data_dir = project_dir.joinpath("data")
model_dir = project_dir.joinpath("model")


def quick_train():
    if not focus_flags:
        logger.warning("Skip model training, miss focus-flags")
        return

    # Copy the classified data into the dataset
    for task_name in focus_flags:
        to_dir = factory_data_dir.joinpath(task_name)
        shutil.rmtree(to_dir, ignore_errors=True)
        to_dir.mkdir(parents=True, exist_ok=True)

        # Flush dataset
        src_dir = binary_dir.joinpath(task_name)
        for hook in ["yes", "bad"]:
            shutil.copytree(src_dir.joinpath(hook), to_dir.joinpath(hook))

        # train
        Scaffold.train(task=task_name)


if __name__ == "__main__":
    # Edit `focus_flags`

    # fmt:off
    focus_flags = {
        # "<diagnosed_label_name>": "<model_name[flag]>"
        # "owl": "owl2309",
        # "beverage": "beverage2312",
        # "food_or_beverage_item": "food_or_beverage_item2311",
        # "boat": "boat2310",
        "bird": "bird2309",
    }
    # fmt:on

    quick_train()
```
