### ISSUE TITLE
fix(bug): ActionChains StaleElementReferenceException

### ISSUE THREAD

**Issue by ICUBICI** [QIN2DIM/hcaptcha-challenger#92]
I get the error:
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
when running main.py demo. This error only occurs on certain instances and seems to be at random. So if anyone could explain why this is happening and if there is a fix to it, it would be appreciated. Thanks!

![image](https://user-images.githubusercontent.com/63574100/180103460-a795912e-325c-4691-994c-2a416268b37f.png)

**Comment by QIN2DIM** [comment]
I need the full exception log

**Comment by ICUBICI** [comment]
Ok here is the full error: 
Traceback (most recent call last):
  File "C:\Users\camca\Downloads\Cubics Member Generator v3\Cubics Member Generator v3\captcha\main.py", line 11, in <module>
    Fire(Scaffold)
  File "C:\Users\camca\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\camca\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\camca\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\camca\Downloads\Cubics Member Generator v3\Cubics Member Generator v3\captcha\services\scaffold.py", line 69, in demo
    challenge.runner(
  File "C:\Users\camca\Downloads\Cubics Member Generator v3\Cubics Member Generator v3\captcha\apis\scaffold\challenge.py", line 61, in runner
    resp = challenger.anti_hcaptcha(ctx)
> File "C:\Users\camca\Downloads\Cubics Member Generator v3\Cubics Member Generator v3\captcha\services\hcaptcha_challenger\core.py", line 637, in anti_hcaptcha
    self.challenge(ctx, solution)
  File "C:\Users\camca\Downloads\Cubics Member Generator v3\Cubics Member Generator v3\captcha\services\hcaptcha_challenger\core.py", line 463, in challenge
    action.perform()
  File "C:\Users\camca\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\action_chains.py", line 75, in perform
    self.w3c_actions.perform()
  File "C:\Users\camca\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\actions\action_builder.py", line 88, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "C:\Users\camca\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\camca\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=103.0.5060.134)
Stacktrace:
Backtrace:
        Ordinal0 [0x003B5FD3+2187219]
        Ordinal0 [0x0034E6D1+1763025]
        Ordinal0 [0x00263E78+802424]
        Ordinal0 [0x00266854+813140]
        Ordinal0 [0x00266712+812818]
        Ordinal0 [0x002669A0+813472]
        Ordinal0 [0x0029779E+1013662]
        Ordinal0 [0x00296E0A+1011210]
        Ordinal0 [0x002C41A3+1196451]
        Ordinal0 [0x002ACB8C+1100684]
        Ordinal0 [0x002BCFC2+1167298]
        Ordinal0 [0x002AC9A6+1100198]
        Ordinal0 [0x00286F80+946048]
        Ordinal0 [0x00287E76+949878]
        GetHandleVerifier [0x006590C2+2721218]
        GetHandleVerifier [0x0064AAF0+2662384]
        GetHandleVerifier [0x0044137A+526458]
        GetHandleVerifier [0x00440416+522518]
        Ordinal0 [0x00354EAB+1789611]
        Ordinal0 [0x003597A8+1808296]
        Ordinal0 [0x00359895+1808533]
        Ordinal0 [0x003626C1+1844929]
        BaseThreadInitThunk [0x76396739+25]
        RtlGetFullPathName_UEx [0x777F8FEF+1215]
        RtlGetFullPathName_UEx [0x777F8FBD+1165]


![image](https://user-images.githubusercontent.com/63574100/180116930-929b789a-a33c-460c-b7b3-2b7bc8e6fe4c.png)
