### ISSUE TITLE
use playwright dmmo question

### ISSUE THREAD

**Issue by xuebotao** [QIN2DIM/hcaptcha-challenger#984]
i use demo_normal_playwright.py demo ,found a error：
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 1: invalid start byte

Detailed error：
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\hcaptcha-challenger\examples\demo_normal_playwright.py", line 143, in <module>
    asyncio.run(bytedance())
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\User\PycharmProjects\hcaptcha-challenger\hcaptcha_challenger\agents\playwright\control.py", line 189, in handler
    data= await response.json()
  File "C:\Users\User\PycharmProjects\ecom-csv-parser\venv\lib\site-packages\playwright\async_api\_generated.py", line 614, in json
    return mapping.from_maybe_impl(await self._impl_obj.json())
  File "C:\Users\User\PycharmProjects\ecom-csv-parser\venv\lib\site-packages\playwright\_impl\_network.py", line 613, in json
    return json.loads(await self.text())
  File "C:\Users\User\PycharmProjects\ecom-csv-parser\venv\lib\site-packages\playwright\_impl\_network.py", line 610, in text
    return content.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 1: invalid start byte
2024-06-06 15:37:35 | ERROR - task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}

Process finished with exit code 0

**Comment by BrynGibson** [comment]
see here: https://github.com/QIN2DIM/hcaptcha-challenger/issues/976

**Comment by xth24** [comment]
> i use demo_normal_playwright.py demo ,found a error： UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 1: invalid start byte
> 
> Detailed error： Traceback (most recent call last): File "C:\Users\User\PycharmProjects\hcaptcha-challenger\examples\demo_normal_playwright.py", line 143, in asyncio.run(bytedance()) File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete self.run_forever() File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever super().run_forever() File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever self._run_once() File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once handle._run() File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run self._context.run(self._callback, *self._args)
> 
> > File "C:\Users\User\PycharmProjects\hcaptcha-challenger\hcaptcha_challenger\agents\playwright\control.py", line 189, in handler
> > data= await response.json()
> > File "C:\Users\User\PycharmProjects\ecom-csv-parser\venv\lib\site-packages\playwright\async_api_generated.py", line 614, in json
> > return mapping.from_maybe_impl(await self._impl_obj.json())
> > File "C:\Users\User\PycharmProjects\ecom-csv-parser\venv\lib\site-packages\playwright_impl_network.py", line 613, in json
> > return json.loads(await self.text())
> > File "C:\Users\User\PycharmProjects\ecom-csv-parser\venv\lib\site-packages\playwright_impl_network.py", line 610, in text
> > return content.decode()
> > UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 1: invalid start byte
> > 2024-06-06 15:37:35 | ERROR - task interrupt  - {'reason': 'Failed to obtain challenge task'}
> 
> Process finished with exit code 0

Set "accept" header to application/json
